env:
  commonjs: true
  es2020: true
  node: true
extends:
    - 'eslint:recommended'
    - 'p5js'
parserOptions:
  ecmaVersion: 11
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
