language: node_js
node_js:
  - 12
before_install:
  - "echo \"Test: echo before_install stage\" && exit 0"
  - "npm install"
install:
  - "echo \"Test: echo install stage\" && exit 0"
before_script:
  - "echo \"Test: echo before_script stage\" && exit 0"
script:
  - "echo \"Test: echo script stage\" && exit 0"
  - "npx eslint helloworld-sketch.js && echo "${PIPESTATUS}""
before_cache:
  - "echo \"Test: echo before_cache stage\" && exit 0"
after_success:
  - "echo \"Test: echo after_success stage\" && exit 0"
after_failure:
  - "echo \"Test: echo after_failure stage\" && exit 0"
before_deploy:
  - "echo \"Test: echo before_deploy stage\" && exit 0"
after_deploy:
  - "echo \"Test: echo after_deploy stage\" && exit 0"
after_script:
  - "echo \"Test: echo after_script stage\" && exit 0"
